trigger:
- none

pr:
- main
- releases/*

workspace:
  clean: all

pool:
  name: Core

variables:
  system.debug: true
  
steps:

- script: |
    echo $(System.PullRequest.TargetBranch)
    echo $(System.PullRequest.targetBranchName)
    echo $(System.PullRequest.SourceRepositoryUri)
    echo $(System.PullRequest.SourceBranch)
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
    echo $(Build.SourceVersion)
    echo $(System.PullRequest.PullRequestId)
    echo $(System.PullRequest.PullRequestNumber)
    
- script: |
    cd $(Build.ArtifactStagingDirectory)
    git clone git clone $(System.PullRequest.SourceRepositoryUri) --branch $(System.PullRequest.TargetBranch) --single-branch --depth 1 .
    $branchName = "$(Build.SourceBranch)".replace("refs/","")
    git pull origin $branchName 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $fso = Get-ChildItem -Recurse -path $(Build.SourcesDirectory)
      
      $fsoBU = Get-ChildItem -Recurse -path $(Build.ArtifactStagingDirectory)
      
      Compare-Object -ReferenceObject $fso -DifferenceObject $fsoBU
