trigger:
- none

pr:
- main
- releases/*

pool:
  vmImage: windows-latest

steps:
- checkout: none
- script: |
    echo $(System.PullRequest.TargetBranch)
    echo $(System.PullRequest.targetBranchName)
    echo $(System.PullRequest.SourceRepositoryUri)
    echo $(System.PullRequest.SourceBranch)
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
- script: |
    git clone $(System.PullRequest.SourceRepositoryUri) --branch $(Build.SourceBranch) --single-branch
