trigger:
- none

pr:
- main
- releases/*

pool:
  vmImage: windows-latest

variables:
  system.debug: true
  
steps:
- checkout: none
- script: |
    echo $(System.PullRequest.TargetBranch)
    echo $(System.PullRequest.targetBranchName)
    echo $(System.PullRequest.SourceRepositoryUri)
    echo $(System.PullRequest.SourceBranch)
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
- script: |
    git clone "https://github.com/nzenginel/demo.git" --branch $(Build.SourceBranch) --single-branch --depth 1
