trigger:
- none

pr:
- main
- releases/*

workspace:
  clean: all

pool:
  name: Core

variables:
  system.debug: true
  
steps:
- checkout: none
  
- task: PowerShell@2
  displayName: 'Display PR Info'
  inputs:
    targetType: 'inline'
    script: |
      echo "PR Repo: $(System.PullRequest.SourceRepositoryUri)"
      echo "PR Number: $(System.PullRequest.PullRequestNumber)"
      echo "Source Branch: $(System.PullRequest.SourceBranch)"
      echo "Target Branch: $(System.PullRequest.TargetBranch)"

- task: PowerShell@2
  displayName: Get merged code
  inputs:
    targetType: 'inline'
    script: |
      git clone $(System.PullRequest.SourceRepositoryUri) --branch $(System.PullRequest.TargetBranch) --single-branch --depth 1 .
      $branch = "$(Build.SourceBranch)"
      $branchName = $branch.replace("refs/","")
      git pull origin $branchName 

