trigger:
- none

pr:
- main
- releases/*

workspace:
  clean: all

pool:
  name: Core

variables:
  system.debug: true
  
steps:
- checkout: none
  
- task: PowerShell@2
  displayName: Get merged code
  inputs:
    targetType: 'inline'
    script: |
      git clone $(System.PullRequest.SourceRepositoryUri) --branch $(System.PullRequest.TargetBranch) --single-branch --depth 1 .
      $branch = "$(Build.SourceBranch)"
      $branchName = $branch.replace("refs/","")
      git pull origin $branchName 

